apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: https://github.com/REPLACE_OWNER/gke-gitops-infra.git
    targetRevision: main
    path: apps/microservice/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: microservice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
